version: "3.9"
services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_DB=zerend
      - POSTGRES_USER=zbokostya
      - POSTGRES_PASSWORD=zbokostya
      - TZ=UTC
      - PGTZ=UTC
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d

  java-yandex-service:
    image: java-yandex-service
    restart: always
    build:
      context: ../../..
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:8080"
    depends_on:
      postgres:
        condition: service_started

volumes:
  pg_data:
    driver: local
